// Starter templates. Each is a complete, sendable email that leans on merge
// fields, fallbacks and a little variation so two contacts never get the
// same sentence. Copied into a user's own templates on request; the copy is
// theirs to edit.
export interface LibraryTemplate { key: string; name: string; category: string; description: string; subject: string; body_html: string; ai_brief: string }

const p = (...lines: string[]) => lines.map((l) => `<p>${l}</p>`).join('');

export const LIBRARY: LibraryTemplate[] = [
  { key: 'cold-intro', name: 'Cold intro · one clear ask', category: 'outreach', description: 'First touch to someone who does not know you. One reason, one ask.',
    subject: '{Quick question|A question} about {{company|your team}}',
    body_html: p('{Hi|Hello} {{first_name|there}},', 'I run {{sender_company|a small team}} and we help companies like {{company|yours}} with [the one thing you do]. {{#if title}}Given your role as {{title}}, {{/if}}I thought it might be relevant.', 'Would a 15 minute call {next week|this week} be worth it? If not, a one-line no is completely fine.', '{Best|Thanks|Regards},<br>{{sender_first_name}}'),
    ai_brief: 'Cold introduction from the sender to a new contact. Explain in one sentence what the sender does and why it matters to the recipient, then ask for a short call.' },
  { key: 'warm-intro', name: 'Warm intro · mutual connection', category: 'outreach', description: 'When someone referred you or you met briefly.',
    subject: '{{referrer|A mutual contact}} suggested I reach out',
    body_html: p('Hi {{first_name|there}},', '{{referrer|A mutual contact}} mentioned you might be looking at [topic] and suggested we talk.', 'In short: we help {{company|teams like yours}} [outcome]. Happy to share how in a quick call, or send a short summary if you would rather read.', 'Would {Tuesday|Wednesday|Thursday} work?', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Warm introduction via a mutual contact named in the referrer field. Mention the referrer once, state the value in one sentence, propose a call.' },
  { key: 'follow-up-1', name: 'Follow-up 1 · gentle nudge', category: 'follow-up', description: 'Three to four days after the first email, same thread.',
    subject: '',
    body_html: p('Hi {{first_name|there}},', 'Just floating this back up in case it got buried. {The short version|In one line}: [the value in one sentence].', 'Worth a quick chat?', '{{sender_first_name}}'),
    ai_brief: 'Short follow-up in the same thread. Restate the value in one sentence and ask again, lightly.' },
  { key: 'follow-up-2', name: 'Follow-up 2 · add something new', category: 'follow-up', description: 'A week later. Bring a new fact, not a reminder.',
    subject: '',
    body_html: p('Hi {{first_name|there}},', 'One thing I should have led with: [a concrete result, number or example relevant to {{company|their business}}].', 'If that is interesting, I can walk you through it in 15 minutes. If the timing is wrong, tell me when to check back.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Second follow-up that adds a new concrete proof point rather than repeating the ask.' },
  { key: 'breakup', name: 'Break-up · last message', category: 'follow-up', description: 'Closes the loop politely and often gets the reply.',
    subject: '',
    body_html: p('Hi {{first_name|there}},', 'I will stop here so I am not cluttering your inbox. If [problem] comes up later, my door is open.', '{Wishing you a good {{weekday}}|All the best},<br>{{sender_first_name}}'),
    ai_brief: 'Final, graceful message ending the sequence with no pressure and an open door.' },
  { key: 'customer-checkin', name: 'Customer check-in', category: 'customer', description: 'Existing customer, no agenda beyond listening.',
    subject: 'How are things going at {{company|your end}}?',
    body_html: p('{{greeting}} {{first_name|there}},', 'Checking in, no agenda. How has [product/service] been working for {{company|you}} lately?', 'If anything is rough around the edges, reply here and I will look at it personally.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Friendly check-in with an existing customer. Ask how things are going, offer help, no selling.' },
  { key: 'upsell', name: 'Upsell · relevant add-on', category: 'customer', description: 'Introduce one add-on tied to how they already use you.',
    subject: 'Something that might fit how {{company|you}} use us',
    body_html: p('Hi {{first_name|there}},', 'Since {{company|your team}} already uses [feature], you might get real mileage out of [add-on]: [what it does in one sentence].', 'Want me to switch it on for a trial, or send a two-minute overview first?', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Offer one relevant add-on to an existing customer, tied to how they already use the product.' },
  { key: 'win-back', name: 'Win-back · lapsed customer', category: 'customer', description: 'For customers who went quiet.',
    subject: 'We miss {{company|you}} a little',
    body_html: p('Hi {{first_name|there}},', 'It has been a while. A lot changed on our side since {{company|you}} last used us: [two improvements].', 'If you would like to have another look, I can set you up with [offer]. And if we lost you for a reason, I would genuinely like to hear it.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Win back a lapsed customer: mention what improved, make a modest offer, invite honest feedback.' },
  { key: 'feedback', name: 'Feedback request', category: 'customer', description: 'Ask one question, make it easy to answer.',
    subject: 'One question about your experience',
    body_html: p('Hi {{first_name|there}},', 'Would you answer one question for me? What is the one thing we could do better for {{company|you}}?', 'A single sentence back is perfect. It goes straight to the people who build the product.', 'Thank you,<br>{{sender_first_name}}'),
    ai_brief: 'Ask a customer for one piece of feedback, framed so a one-line reply is enough.' },
  { key: 'testimonial', name: 'Testimonial ask', category: 'customer', description: 'After a good outcome.',
    subject: 'Could we quote you?',
    body_html: p('Hi {{first_name|there}},', 'Glad [outcome] worked out. Would you be open to a two-sentence quote we can use on our site? I can draft something for you to edit so it takes a minute.', 'Either way, thanks for working with us.', '{{sender_first_name}}'),
    ai_brief: 'Ask a happy customer for a short testimonial and offer to draft it for them.' },
  { key: 'referral', name: 'Referral ask', category: 'customer', description: 'Ask a happy customer for one introduction.',
    subject: 'A small favour',
    body_html: p('Hi {{first_name|there}},', 'Is there one person in your network dealing with [problem] who would benefit from what we did for {{company|you}}? An intro from you would mean a lot; happy to make it easy with a one-paragraph blurb.', 'Thanks either way,<br>{{sender_first_name}}'),
    ai_brief: 'Ask a satisfied customer for a single introduction and offer to provide a short blurb.' },
  { key: 'event-invite', name: 'Event invitation', category: 'invite', description: 'Webinar, meetup or open house.',
    subject: 'You are invited: {{event_name|our next event}} on {{event_date|the date}}',
    body_html: p('Hi {{first_name|there}},', 'We are hosting {{event_name|an event}} on {{event_date|soon}}{{#if event_location}} at {{event_location}}{{/if}}. It covers [topic] and I think it fits what {{company|you}} are working on.', 'Would you like a seat? Reply yes and I will hold one for you.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Invite the contact to an event using the event_name, event_date and event_location fields.' },
  { key: 'meeting-confirm', name: 'Meeting confirmation', category: 'scheduling', description: 'Confirm time, place and agenda.',
    subject: 'Confirmed: {{meeting_time|our call}}',
    body_html: p('Hi {{first_name|there}},', 'Confirming our {{meeting_type|call}} on {{meeting_time|the agreed time}}. Agenda: [two points]. If anything comes up, reply here and we will move it.', 'Talk soon,<br>{{sender_first_name}}'),
    ai_brief: 'Confirm a scheduled meeting with time and a two-point agenda.' },
  { key: 'reschedule', name: 'Reschedule request', category: 'scheduling', description: 'Move a meeting without drama.',
    subject: 'Can we move {{meeting_time|our call}}?',
    body_html: p('Hi {{first_name|there}},', 'Something came up on my side and I need to move our {{meeting_type|call}}. Could you do {{alt_time_1|another slot}}{{#if alt_time_2}} or {{alt_time_2}}{{/if}} instead?', 'Sorry for the shuffle,<br>{{sender_first_name}}'),
    ai_brief: 'Politely ask to reschedule a meeting and propose alternative times.' },
  { key: 'thank-you', name: 'Thank you after a call', category: 'follow-up', description: 'Same day, with the next step.',
    subject: 'Thanks, and next steps',
    body_html: p('Hi {{first_name|there}},', 'Thanks for the time today. What I took away: [one line]. Next step on my side: [action] by {{next_step_date|the end of the week}}.', 'Anything I missed?', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Thank the contact for a call, summarise the takeaway in one line, state the next step.' },
  { key: 'onboarding-welcome', name: 'Welcome · onboarding', category: 'customer', description: 'First message after signup.',
    subject: 'Welcome aboard, {{first_name|and hello}}',
    body_html: p('Hi {{first_name|there}},', 'Welcome to {{sender_company|the team}}. Three things worth doing this week: [step one], [step two], [step three].', 'I am your point of contact. Reply to this email any time and a person answers.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Welcome a new customer with three concrete first steps and a named point of contact.' },
  { key: 'product-update', name: 'Product update', category: 'announcement', description: 'One improvement, why it matters, how to use it.',
    subject: 'New: {{feature_name|an improvement}} for {{company|you}}',
    body_html: p('Hi {{first_name|there}},', 'We shipped {{feature_name|something new}}: [what it does]. For {{company|you}} that means [benefit].', 'It is on already. [Where to find it]. Questions, reply here.', '{{sender_first_name}}'),
    ai_brief: 'Announce one product improvement, explain the benefit for this contact, say where to find it.' },
  { key: 'invoice-reminder', name: 'Invoice reminder', category: 'payment', description: 'Friendly, factual, with the amount and date.',
    subject: 'Invoice {{invoice_number|reminder}}{{#if amount}} · {{amount}}{{/if}}',
    body_html: p('Hi {{first_name|there}},', 'A quick reminder that invoice {{invoice_number|from us}}{{#if amount}} for {{amount}}{{/if}} was due on {{due_date|its due date}}. If it has already gone out, thank you and please ignore this.', 'If anything is unclear on the invoice, reply and I will sort it out.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Polite payment reminder using invoice_number, amount and due_date.' },
  { key: 'partnership', name: 'Partnership proposal', category: 'outreach', description: 'Propose working together, mutual benefit first.',
    subject: 'An idea for {{company|us}} + {{sender_company|us}}',
    body_html: p('Hi {{first_name|there}},', 'I have been following {{company|your work}} and think there is a natural fit: [what each side brings]. Concretely, [one joint idea].', 'Open to a 20 minute call to see if it is real?', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Propose a partnership with a concrete joint idea and a short call.' },
  { key: 'reactivation', name: 'Reactivation · dormant lead', category: 'outreach', description: 'Someone who showed interest months ago.',
    subject: 'Still relevant, {{first_name|there}}?',
    body_html: p('Hi {{first_name|there}},', 'We spoke a while back about [topic]. Things may have moved on, so a quick check: is this still on your list for {{year}}?', 'If yes, I have something new to show you. If no, thanks for the honesty and I will close the file.', '{{sender_first_name}}'),
    ai_brief: 'Reactivate a dormant lead by asking whether the topic is still relevant this year.' },
  { key: 'holiday', name: 'Holiday greeting', category: 'announcement', description: 'Short, warm, no pitch.',
    subject: '{Happy holidays|Season’s greetings} from {{sender_company|all of us}}',
    body_html: p('Hi {{first_name|there}},', 'No pitch in this one. Thank you for {working with us|the conversations} this year. Wishing you and {{company|your team}} a restful break.', 'See you in the new year,<br>{{sender_first_name}}'),
    ai_brief: 'Warm holiday greeting with no sales content.' },
  { key: 'reply-pricing', name: 'Reply · pricing question', category: 'reply', description: 'Answer a pricing question without a wall of numbers.',
    subject: '',
    body_html: p('Hi {{first_name|there}},', 'Good question. Pricing depends on [the one variable]; for {{company|a team like yours}} it usually lands around [range]. I would rather give you an exact number than a range, so: [one clarifying question]?', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Answer a pricing question with a typical range and one clarifying question.' },
  { key: 'reply-not-now', name: 'Reply · "not now"', category: 'reply', description: 'When they say the timing is wrong.',
    subject: '',
    body_html: p('Hi {{first_name|there}},', 'Understood, thanks for telling me. I will check back in {{check_back|a few months}} unless you say otherwise. If anything changes sooner, you know where I am.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Graceful reply to a "not now" that sets a check-back time.' },
  { key: 'reply-scheduling', name: 'Reply · propose times', category: 'reply', description: 'Turn a yes into a booked slot.',
    subject: '',
    body_html: p('Great, {{first_name|thanks}}. Would any of these work? {{slot_1|Tuesday 10:00}}, {{slot_2|Wednesday 14:00}} or {{slot_3|Thursday 11:00}} ({{timezone|your time}}). If none do, send me two options and I will take one.', 'Best,<br>{{sender_first_name}}'),
    ai_brief: 'Reply to a yes with three proposed time slots.' },
  { key: 'apology-delay', name: 'Apology · delayed reply', category: 'reply', description: 'Own the delay, then answer.',
    subject: '',
    body_html: p('Hi {{first_name|there}},', 'Apologies for the slow reply; that is on me. To your question: [answer].', 'Thanks for your patience,<br>{{sender_first_name}}'),
    ai_brief: 'Apologise briefly for a late reply and answer the original question.' },
];

export const LIBRARY_CATEGORIES = [...new Set(LIBRARY.map((t) => t.category))];
